CREATE OR REPLACE TABLE TN_PGUSR (
	USR_ID BIGINT NOT NULL  COMMENT '사용자테이블',
	USR_PWD VARCHAR(100) NOT NULL COMMENT '비밀번호',
	USR_ROLE VARCHAR(100) NOT NULL COMMENT '권한',
	USR_TEAM VARCHAR(100) NOT NULL COMMENT '소속',
	USR_POSITION VARCHAR(100) NULL COMMENT '직급',
	REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록날짜',
	MOD_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '수정날짜',
	RECENT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '최근접속날짜',
	CONSTRAINT TN_PGUSR_PK PRIMARY KEY (USR_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='사용자테이블' ;

