-- 사용자 테이블
CREATE OR REPLACE TABLE TN_SRV_USER (
	USER_ID VARCHAR(100) NOT NULL  COMMENT '사용자아이디',
	USER_PWD VARCHAR(100) NOT NULL COMMENT '비밀번호',
	USER_ROLE VARCHAR(100) NULL COMMENT '권한',
	USER_TEAM VARCHAR(100) NULL COMMENT '소속',
	USER_PSTN VARCHAR(100) NULL COMMENT '직급',
	INST_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록날짜',
	UPDT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '수정날짜',
	CONSTRAINT TN_SRV_USER_PK PRIMARY KEY (USER_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='사용자테이블';


-- 설문지 관리테이블 
CREATE OR REPLACE TABLE TN_SRV_MSTR (
	SRV_MSTR_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '설문지 관리테이블 SEQ',
	CAT_MSTR_ID BIGINT NULL COMMENT '카테고리 테이블 시퀀스',
	TMP_MSTR_ID BIGINT NULL COMMENT '템플릿 관리테이블 시퀀스',
	SRV_MST_NM varchar(100) NULL COMMENT '설문지명',
	INST_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록날짜',
	UPDT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '수정날짜',
	PBSH_DT TIMESTAMP NULL COMMENT '게시날짜',
	EXPR_DT TIMESTAMP NULL COMMENT '만료날짜',
	INST_USRID varchar(100) NULL COMMENT '등록 아이디',
	UPDT_USRID varchar(100) NULL COMMENT '수정 아이디',
	CONSTRAINT TN_SRV_MSTR_PK PRIMARY KEY (SRV_MSTR_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='설문지 관리테이블';


-- 설문지문항 관리테이블
CREATE OR REPLACE TABLE TN_SRV_QSTN (
	SRV_QSTN_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '설문지문항 관리테이블 시퀀스',
	SRV_QSTN_TITLE varchar(100) NULL COMMENT '설문지 문항제목',
	SRV_MSTR_ID BIGINT NULL COMMENT '설문지 관리테이블',
	SRV_QSTN_ODR INT NULL COMMENT '설문지 문항순서',
	SRV_QSTN_FLG VARCHAR(1) NULL COMMENT '설문지 문항 플래그값',
	INST_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록날짜',
	UPDT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '수정날짜',
	INST_USRID varchar(100) NULL COMMENT '등록 아이디',
	UPDT_USRID varchar(100) NULL COMMENT '수정 아이디',
	CONSTRAINT TN_SRV_QSTN_PK PRIMARY KEY (SRV_QSTN_ID,SRV_MSTR_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='설문지문항 관리테이블';

-- 설문지 객곽신문항 관리테이블
CREATE OR REPLACE TABLE TN_SRV_OBJT (
	SRV_OBJT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '설문지 객관식문항 시퀀스',
	SRV_OBJT_CNTNT varchar(255) NULL COMMENT '설문지 객관식 문항내용',
	SRV_QSTN_ID BIGINT NULL COMMENT '설문지 문항 시퀀스',
	SRV_OBJT_NUM INT NULL COMMENT '설문지 객관식 문항번호',
	INST_USRID varchar(100) NULL COMMENT '등록 아이디',
	UPDT_USRID varchar(100) NULL COMMENT '수정 아이디',
	CONSTRAINT TN_SRV_OBJT_PK PRIMARY KEY (SRV_OBJT_ID,SRV_QSTN_ID,SRV_OBJT_NUM)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='설문지 객관식 문항관리테이블' ;

-- 설문응답 관리테이블
CREATE OR REPLACE TABLE TN_SRV_RESPNS (
	SRV_RESPNS_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '설문지 응답시퀀스',
	SRV_MSTR_ID BIGINT NULL COMMENT '설문지 관리시퀀스',
	SRV_OSTN_ID BIGINT NULL COMMENT '설문지 문항시퀀스',
	SRV_RESPNS_VAL varchar(255) NULL COMMENT '설문 응답내용',
	INST_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록날짜',
	UPDT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '수정날짜',
	INST_USRID varchar(100) NULL COMMENT '등록 아이디',
	CONSTRAINT TN_SRV_RESPNS_PK PRIMARY KEY (SRV_RESPNS_ID,SRV_MSTR_ID,SRV_OSTN_ID,INST_USRID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='설문응답 관리테이블' ;

-- 카테고리 관리테이블 보류....
CREATE OR REPLACE TABLE TN_CAT_MSTR (
	CAT_MSTR_ID BIGINT NULL AUTO_INCREMENT COMMENT '카테고리 관리시퀀스',
	CAT_MSTR_CODE varchar(100) NULL COMMENT '카테고리분류 코드',
	CONSTRAINT TN_CAT_MSTR_PK PRIMARY KEY (CAT_MSTR_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='카테고리 관리테이블' ;

-- 공통코드 그룹테이블
CREATE TABLE TN_CDE_GROP (
	CDE_GROP_CODE varchar(100) NOT NULL COMMENT '공통코드 그룹코드',
	CDE_GROP_VAL varchar(100) NOT NULL COMMENT '공통코드 그룹값',
	INST_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록날짜',
	UPDT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '수정날짜',
	INST_USRID varchar(100) NULL COMMENT '등록 아이디',
	CONSTRAINT TN_CDE_GROP_PK PRIMARY KEY (CDE_GROP_CODE)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='공통코드 그룹테이블' ;


-- 공통코드 관리테이블
CREATE OR REPLACE TABLE TN_CDE_MSTR (
	CDE_MSTR_CODE varchar(100) NOT NULL COMMENT '공통코드',
	CDE_MSTR_VAL varchar(100) NULL COMMENT '공통코드값',
	CDE_GROP_CODE varchar(100) NULL COMMENT '공통코드 그룹코드',
	INST_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록날짜',
	UPDT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '수정날짜',
	INST_USRID varchar(100) NULL COMMENT '등록 아이디',
	CONSTRAINT TN_CDE_MSTR_PK PRIMARY KEY (CDE_MSTR_CODE,CDE_GROP_CODE)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='공통코드 관리테이블' ;

-- 템플릿 관리테이블
CREATE OR REPLACE TABLE TN_TMP_MSTR (
	TMP_MSTR_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '템플릿 관리아이디',
	TMP_MSTR_DESCPTN varchar(255) NULL COMMENT '템플릿 설명',
	TMP_TYPE_ID BIGINT NULL COMMENT '템플릿 타입',
	TMP_MSTR_TMPLTFILE varchar(255) NULL COMMENT '템플릿 파일경로',
	INST_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록날짜',
	UPDT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '수정날짜',
	INST_USRID varchar(100) NULL COMMENT '등록 아이디',
	UPDT_USRID varchar(100) NULL COMMENT '수정 아이디',
	CONSTRAINT TN_CDE_GROP_PK PRIMARY KEY (TMP_MSTR_ID,TMP_TYPE_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='템플릿 관리테이블' ;

-- 템플릿 유형테이블
CREATE OR REPLACE TABLE TN_TMP_TYPE (
	TMP_TYPE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '템플릿 유형아이디',
	TMP_TYPE_NM varchar(100) NULL COMMENT '템플릿 유형이름',
	TMP_TYPE_FILE varchar(100) NULL COMMENT '탬플릿 유형파일경로',
	INST_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록날짜',
	UPDT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '수정날짜',
	INST_USRID varchar(100) NULL COMMENT '등록 아이디',
	UPDT_USRID varchar(100) NULL COMMENT '수정 아이디',
	CONSTRAINT TN_TMP_TYPE_PK PRIMARY KEY (TMP_TYPE_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='템플릿 유형테이블' ;


-- 공통 
CREATE TABLE ACTION_MAPPING (
	ACTION_ID varchar(100) NOT NULL COMMENT '액션아이디',
	CLASS_NM varchar(100)  NOT NULL COMMENT '클래스명(패키지포함)',
	CLASS_METHOD varchar(100) NOT NULL COMMENT '함수명',
	PAGE_NM varchar(100) NOT NULL COMMENT '화면명(경로포함)',
	ACTION_TYPE varchar(100) DEFAULT 'N' NOT NULL COMMENT '액션타입',
	INST_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록날짜',
	CONSTRAINT ACTION_MAPPING_PK PRIMARY KEY (ACTION_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='액션매핑 테이블' ;