-- 설문지 관리테이블 
CREATE OR REPLACE TABLE TN_SRV_MSTR (
	SRV_MSTR_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '설문지 관리아이디',
	SRV_MST_NM varchar(100) NULL COMMENT '설문지명',
	SRV_MST_TG varchar(100) DEFAULT NULL COMMENT '설문대상',
	SRV_MST_DC varchar(100) NULL COMMENT '설문지설명',
	INST_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록날짜',
	UPDT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '수정날짜',
	PBSH_DT TIMESTAMP NULL COMMENT '게시날짜',
	EXPR_DT TIMESTAMP NULL COMMENT '만료날짜',
	INST_USRID varchar(100) NULL COMMENT '등록 아이디',
	UPDT_USRID varchar(100) NULL COMMENT '수정 아이디',
	CONSTRAINT TN_SRV_MSTR_PK PRIMARY KEY (SRV_MSTR_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='설문지 관리테이블';

-- 응답관리테이블
CREATE OR REPLACE TABLE TN_SRV_MTRITEMS (
	SRV_MTRITEMS_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '응답항목관리아이디',
	SRV_MSTR_ID BIGINT NOT NULL COMMENT '설문지관리아이디',
	SRV_MTRITEMS_TITLE varchar(100) NULL COMMENT '응답항목명',
	SRV_MTRITEMS_TYPE INT NULL COMMENT '응답항목타입(0:객관식,1:주관식)',
	INST_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '최초생성시간',
	UPDT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '수정시간',
	CONSTRAINT TN_SRV_MTRITEMS_PK PRIMARY KEY (SRV_MTRITEMS_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='응답항목 관리테이블' ;


-- 응답항목 테이블
CREATE OR REPLACE TABLE TN_SRV_ITEMS (
	SRV_ITEMS_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '응답항목아이디',
	SRV_MSTR_ID BIGINT NOT NULL COMMENT '설문지관리아이디',
	SRV_MTRITEMS_ID BIGINT NOT NULL COMMENT '응답항목관리아이디',
	SRV_ITEM_NM varchar(100) NULL COMMENT '응답내용',
	SRV_ITEM_IDX varchar(100) NULL COMMENT '응답항목순번',
	INST_DT TIMESTAMP NULL COMMENT '최초생성시간',
	UPDT_DT TIMESTAMP NULL COMMENT '수정시간',
	CONSTRAINT TN_SRV_ITEMS_PK PRIMARY KEY (SRV_ITEMS_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='응답항목테이블' ;

-- 응답테이블
CREATE OR REPLACE TABLE TN_SRV_RESPNS (
	SRV_RESPNS_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '설문지 응답시퀀스',
	SRV_MSTR_ID BIGINT NULL COMMENT '설문지 관리시퀀스',
	SRV_MTRITEMS_ID BIGINT NOT NULL COMMENT '응답항목관리아이디',
	SRV_RESPNS_CODE INT DEFAULT 0 NOT NULL COMMENT '분류응답코드',
	SRV_RESPNS_VALUE varchar(1024) DEFAULT NULL COMMENT '설문지응답내용',
	INST_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록날짜',
	UPDT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '수정날짜',
	INST_USRID varchar(100) NULL COMMENT '등록 아이디',
	CONSTRAINT TN_SRV_RESPNS_PK PRIMARY KEY (SRV_RESPNS_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='설문응답 관리테이블' ;

-- 설문응답통계테이블
CREATE OR REPLACE TABLE TN_SRV_RESPNSTT (
	SRV_RESPNSTT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '설문응답통계아이디',
	SRV_MSTR_ID BIGINT NOT NULL COMMENT '설문지관리아이디',
	SRV_MTRITEMS_ID BIGINT NOT NULL COMMENT '응답항목관리아이디',
	SRV_RESPNS_VALUE varchar(1024) DEFAULT NULL COMMENT '설문지응답내용',
	SRV_RESPNS_CODE INT DEFAULT 0 NOT NULL COMMENT '분류응답코드',
	SRV_RESPNSTT_CNT BIGINT NOT NULL COMMENT '응답수',
	SRV_RESPNSTT_TOTAL BIGINT NOT NULL COMMENT '응답총수',
	INST_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '생성시간',
	UPDT_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL COMMENT '수정시간',
	INST_USRID varchar(100) NULL COMMENT '등록사용자',
	CONSTRAINT TN_SRV_RESPNSTT_PK PRIMARY KEY (SRV_RESPNSTT_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci
COMMENT='설문응답통계테이블' ;


